### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by Jinkxed** [mgyucht/slackbot-workout#110]
Would you mine updating the readme, it seems a little off.

Currently doing:

```
python -m samples.flexbot
/usr/bin/python: No module named samples.flexbot
```

Returns no module loaded.

What is the preferred way to run this now?

Thanks for the updated work on it, very cool project.

**Comment by ollu** [comment]
I too run into the this problem when trying to start the application.
I guess that it should be
`$ python -m samples.run_flexbot`

**Comment by mgyucht** [comment]
Gotcha, will do! Sorry I didn't see this until now, for some reason I didn't get an email about it.
