### ISSUE TITLE
In acknowledgment mode, bot should increase exercise count even if you haven't done the exercise

### ISSUE THREAD

**Issue by mgyucht** [mgyucht/slackbot-workout#53]
@jengler what do you think about this behavior? The other option is that you make up for times you missed workouts by doing them later in the day.

**Comment by mgyucht** [comment]
This way basically incentivizes users to do workouts when they're called out since they are opportunities which can be missed.

**Comment by jengler** [comment]
Yeah, I am curious how Hossein and HDD have been finding it. They both missed.
I like the idea of you having to respond or you miss it. I am in favor of allowing you to postpone/makeup exercises. Maybe allow someone to give themselves an exercise.

**Comment by mgyucht** [comment]
The stats should then show how many exercises have been assigned to each user as well.

**Comment by mgyucht** [comment]
This can probably be a configurable option, since it seems like both options may be desirable. Another potential avenue is to allow people to acknowledge an exercise even if someone else has been called out since their original callout. This is good in case you missed an exercise.

**Comment by mgyucht** [comment]
We went with the second option here.
