### ISSUE TITLE
Refactor exercise configuration out of app config

### ISSUE THREAD

**Issue by mgyucht** [mgyucht/slackbot-workout#56]
Both can be dynamically loaded, but the info blocks for exercises make the app config HUGE, and if we want to add other assets or links for exercises or add more exercises, they are only going to get bigger. Better if we come up with another way for specifying exercises to be used by the bot. One thought that I'm having now is to store exercise information as a YAML file, put all the files in one directory, and have the app config include a directory to scan for exercises. Alternatively the app config could include the paths to each exercise separately.

**Comment by mgyucht** [comment]
My plan is:
Leave the exercise format the same as it currently is. Each exercise will exist in its own YAML file which can have an arbitrary name. The user can specify a directory which contains exercises in the main configuration in place of putting the exercises in there directly. The assumed default directory will be the `exercises` directory which will soon be showing up in the repo.

**Comment by mgyucht** [comment]
At startup, the configurator will scan the provided directory for yaml files, and any which contain id, name, min_reps, max_reps, units, and info fields will be loaded.

**Comment by mgyucht** [comment]
As a part of this, I'm also going to make a proper Exercise class.

**Comment by jengler** [comment]
Sounds good :)
